deploy_backend:
  stage: deploy
  script: |
   cd /var/www/html/dawafast-backend 
    sudo git pull  
    sudo php artisan optimize:clear
  tags:
    - dev-backend
    - dawafast
  only:
    - development

Fix_Permission:
  stage: deploy
  dependencies:
    - "deploy_backend"
  script: |
   cd /var/www/html/dawafast-backend 
   sudo chown -R www-data:www-data .
   sudo find -type f -exec chmod 644 {} \;
   sudo find -type d -exec chmod 755 {} \;

  tags:
    - dev-backend
    - dawafast
  only:
    - development
